# Generated by Django 3.0.5 on 2020-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200428_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=1000),
        ),
    ]
